apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

resources:
- 01-configmap.yaml
- 02-secret.yaml
- 03-deployment.yaml
- 04-service.yaml
- 05-hpa.yaml

images:
- name: cr.yandex/crphjp07nodds7bvd5ar/ecommerce-order-service
  newTag: 8c9f90b
