apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: kafka
  labels:
    app: zookeeper
spec:
  ports:
  - port: 2181
    name: client
    targetPort: 2181
  - port: 2888
    name: follower
    targetPort: 2888
  - port: 3888
    name: election
    targetPort: 3888
  clusterIP: None
  selector:
    app: zookeeper