apiVersion: v1
kind: Service
metadata:
  name: wallet-service
  namespace: ecommerce
  labels:
    app: wallet-service
spec:
  type: ClusterIP
  selector:
    app: wallet-service
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: grpc-user
      port: 50050
      targetPort: grpc-user
      protocol: TCP
    - name: grpc-saga
      port: 50054
      targetPort: grpc-saga
      protocol: TCP