apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

resources:
- 01-secret.yaml
- 02-configmap.yaml
- 03-deployment.yaml
- 04-service.yaml
- 05-hpa.yaml
- 06-ingress.yaml

images:
- name: cr.yandex/crphjp07nodds7bvd5ar/ecommerce-wallet-service
  newTag: 025ff12
