apiVersion: v1
kind: Secret
metadata:
  name: sso-service-secret
  namespace: ecommerce
type: Opaque
stringData:
  PG_PASSWORD: "changeme"
  JWT_SECRET: "your-super-secret-jwt-key-change-this-in-production-min-32-chars"