apiVersion: apps/v1
kind: Deployment
metadata:
  name: sso-service
  namespace: ecommerce
  labels:
    app: sso-service
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: sso-service
  template:
    metadata:
      labels:
        app: sso-service
    spec:
      # Секрет для доступа к Yandex Container Registry
      imagePullSecrets:
        - name: yc-registry-secret
      
      containers:
        - name: sso-service
          image: cr.yandex/crphjp07nodds7bvd5ar/ecommerce-sso-service:latest
          imagePullPolicy: Always
          
          ports:
            - name: http
              containerPort: 8080
            - name: grpc
              containerPort: 50051
          
          # Переменные окружения из ConfigMap
          envFrom:
            - configMapRef:
                name: sso-service-config
          
          # Секретные переменные из Secret
          env:
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sso-service-secret
                  key: PG_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sso-service-secret
                  key: JWT_SECRET
          
          # Сколько ресурсов выделить
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi