apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sso-service-ingress
  namespace: ecommerce
spec:
  ingressClassName: nginx
  rules:
    # Замените на ваш реальный домен или IP
    - host: sso.ecommerce.local
      http:
        paths:
          # Все запросы на /api/v1/auth/* идут на sso-service
          - path: /api/v1/auth
            pathType: Prefix
            backend:
              service:
                name: sso-service
                port:
                  number: 8080