apiVersion: v1
kind: ConfigMap
metadata:
  name: wallet-service-config
  namespace: ecommerce
data:
  PG_HOST: "postgres.datastore.svc.cluster.local"
  PG_PORT: "5432"
  PG_USER: "ecommerce"
  PG_NAME: "ecommerce"
  GRPC_USER_SERVER_PORT: "50050"
  GRPC_SAGA_SERVER_PORT: "50054"
  HTTP_GATEWAY_PORT: "8080"
  GRPC_CLIENT_PORT: "sso-service.ecommerce.svc.cluster.local:50051"