apiVersion: v1
kind: Service
metadata:
  name: sso-service
  namespace: ecommerce
  labels:
    app: sso-service
spec:
  type: ClusterIP
  ports:
    # HTTP порт для REST API
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    # gRPC порт для межсервисного взаимодействия
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
  selector:
    app: sso-service