apiVersion: v1
kind: ConfigMap
metadata:
  name: products-service-config
  namespace: ecommerce
data:
  PG_HOST: "postgres.datastore.svc.cluster.local"
  PG_PORT: "5432"
  PG_NAME: "ecommerce"
  PG_USER: "ecommerce"
  
  HTTP_PORT: "8080"
  
  GRPC_PRODUCTS_SERVER_PORT: "50051"
  GRPC_SAGA_SERVER_PORT: "50052"
  
  GRPC_JWT_CLIENT_PORT: "sso-service.ecommerce.svc.cluster.local:50051"