apiVersion: v1
kind: ConfigMap
metadata:
  name: saga-orchestrator-config
  namespace: ecommerce
data:
  PG_HOST: "postgres.datastore.svc.cluster.local"
  PG_PORT: "5432"
  PG_USER: "ecommerce"
  PG_NAME: "ecommerce"
  GRPC_SERVER_PORT: "50051"
  HTTP_HEALTH_PORT: "8080"
  GRPC_WALLET_CLIENT_PORT: "wallet-service.ecommerce.svc.cluster.local:50054"
  GRPC_PRODUCTS_CLIENT_PORT: "products-service.ecommerce.svc.cluster.local:50051"
  # Kafka settings moved to kafka-config ConfigMap