apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-service-config
  namespace: ecommerce
data:
  PG_HOST: "postgres.datastore.svc.cluster.local"
  PG_PORT: "5432"
  PG_USER: "ecommerce"
  PG_NAME: "ecommerce"
  HTTP_PORT: "8080"
  REDIS_ADDR: "redis-service.redis.svc.cluster.local:6379"
  REDIS_DB: "0"
  RATE_LIMIT_RPS: "60"
  MAX_PRODUCT_QUANTITY: "100"
  GRPC_JWT_CLIENT_PORT: "sso-service.ecommerce.svc.cluster.local:50051"
  GRPC_PRODUCTS_CLIENT_PORT: "products-service.ecommerce.svc.cluster.local:50051"
  GRPC_ORDER_CLIENT_PORT: "order-service.ecommerce.svc.cluster.local:50051"
  GRPC_SAGA_CLIENT_PORT: "saga-orchestrator.ecommerce.svc.cluster.local:50051"
  # Kafka is optional - leave empty to run without Kafka
  KAFKA_BROKER: ""
  KAFKA_GROUP_ID: "cart-service-group"
  KAFKA_TOPIC: "order-events"